SimWeb/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SimWeb.Pages
{
    public class AboutModel : PageModel
    {
        public void OnGet()
        {
        }
    }

}

SimWeb/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SimWeb.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

SimWeb/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Simulator;
using Simulator.Maps;

namespace SimWeb.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

SimWeb/Pages/Simulation.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Simulator.Maps;
using Simulator;
using System.Text.Json;
using System.Net.Http.Headers;

namespace SimWeb.Pages
{
    public class SimulationModel : PageModel
    {
        
        public SimulationHistory InitSimHist()
        {
            SmallTorusMap map = new(10, 6);
            List<IMappable> mappables = [new Creeper("Boomer"), new Human("Steve"), new Birds(){Description="Chicks", Size=9, CanFly=false}, new Animals() { Description="Sheep", Size=6 }, new Birds { Description="Ender Dragon", Size=1, CanFly=true}];
            List<Point> points = [new(1, 5), new(0, 1), new(8, 4), new(7, 3), new(3, 4)];
            string moves = !string.IsNullOrWhiteSpace(Moves) ? Moves : "uuuuuuuuu";
            Simulation simulation = new(map, mappables, points, moves);
            SimHist = new(simulation);
            return SimHist;
        }

        public string MakeField(SimulationHistory simulationHistory, int turnIndex)
        {
            var temp_mapb = simulationHistory.TurnLogs.ElementAt(turnIndex);
            string res = "";
            if (turnIndex!=0)
            {
                res += $"<h2>Turn {turnIndex}: {temp_mapb.Mappable.GetType().Name.ToString().ToUpper()}:" +
                $" {temp_mapb.Mappable.Info} {temp_mapb.Mappable.Map!.Next(temp_mapb.Mappable.Position,
                Reverse(DirectionParser.Parse(temp_mapb.Move).ElementAt(0)))} goes {temp_mapb.Move}</h2>";
            }
            else
            {
                res += "<h2>Starting positions:</h2>";
            }
            res += "<div class='main-text'>\r\n    " +
                $"<div class='game-board' style='--columns: {simulationHistory.SizeX}; --rows: {simulationHistory.SizeY}'>";
            for (int i = simulationHistory.SizeY - 1; i >= 0; i--)
            {
                for (int j = 0; j < simulationHistory.SizeX; j++)
                {
                    Point p = new(j, i);
                    res += $"<div class='field'>";
                    res += "<img class='board-icon' ";
                    if (simulationHistory.TurnLogs.ElementAt(turnIndex).Symbols.TryGetValue(p, out char value))
                    {
                        
                        switch(value)
                        {
                            case 'C':
                                res+= "src='/images/creeper-1817227_640.png'>";
                                break;
                            case 'H':
                                res += "src='/images/1559756863Minecraft-Png-steve.png'>";
                                break;
                            case 'b':
                                res += "src='/images/1559756861minecraft-clipart-9_l.png'>";
                                break;
                            case 'B':
                                res += "style='filter: brightness(100%);' src='/images/d57o57e-54ee1f59-6239-473e-8656-91cbf255f45a.gif'>";
                                break;
                            case 'A':
                                res += "src='/images/1559756856minecraft-png-33_l.png'>";
                                break;
                            case 'X':
                                res += "src='/images/questions.png'>";
                                break;
                            default:
                                res += "style='opacity: 0;' src='/images/BackgroundPattern253.svg'>";
                                break;
                        }
                    }
                    else
                    {
                        res += "style='opacity: 0;' src='/images/BackgroundPattern253.svg'>";
                    }
                    res+="</div>";
                }
            }
            res += "</div>\r\n</div>";
            return res;
        }
        
        [BindProperty(SupportsGet = true)]
        public string? Moves { get; set; }
        
        public string? Field { get; set; }
        public int TurnStamp { get; private set; }
        public SimulationHistory? SimHist { get; private set; }
        public void OnGet()
        {
            TurnStamp = 0;
            HttpContext.Session.SetInt32("TurnStamp", TurnStamp);
            HttpContext.Session.SetString("Moves", Moves ?? string.Empty);
            SimHist = InitSimHist();
            Field = MakeField(SimHist, TurnStamp);
        }
        public void OnPostNext()
        {
            TurnStamp = HttpContext.Session.GetInt32("TurnStamp") ?? 0;
            Field = HttpContext.Session.GetString("Field") ?? "AAAAAAAAAA";
            Moves = HttpContext.Session.GetString("Moves") ?? string.Empty;
            if (TurnStamp < Moves?.Length)
            {
                TurnStamp++;
            }
            HttpContext.Session.SetInt32("TurnStamp", TurnStamp);
            SimHist = InitSimHist();
            Field = MakeField(SimHist, TurnStamp);
        }
        public void OnPostPrevious()
        {
            TurnStamp = HttpContext.Session.GetInt32("TurnStamp") ?? 0;
            Moves = HttpContext.Session.GetString("Moves") ?? string.Empty;
            if (TurnStamp > 0)
            {
                TurnStamp--;
            }
            HttpContext.Session.SetInt32("TurnStamp", TurnStamp);
            SimHist = InitSimHist();
            Field = MakeField(SimHist, TurnStamp);
        }

        private static Direction Reverse(Direction d)
        {
            return d switch
            {
                Direction.Up => Direction.Down,
                Direction.Right => Direction.Left,
                Direction.Down => Direction.Up,
                Direction.Left => Direction.Right,
                _ => default,
            };
        }
    }
}

SimWeb/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h1>@ViewData["Title"]</h1>

<div class="main-text">
    My name is Michael Tryfanau, and I am a computer science student in Kraków, Poland. <br /><br />
    This project presents, on its surface, a mashup of the ideas and concepts from the coursework, as well as a popular open-world game from Sweden.<br />
    <br /><br />
    Specifications:
    <p style="font-family: 'Source Code Pro'">SmallTorusMap(10, 6)<br />
    Creeper("Boomer")&zwj;(1,&nbsp;5), Human("Steve")&zwj;(0,&nbsp;1), 
    Birds("Chicks", 9, can't fly)&zwj;(8,&nbsp;4), Animals("Sheep", 6)&zwj;(7,&nbsp;3), 
    Birds("Ender Dragon", 1, Can fly)&zwj;(3,&nbsp;4);
    </p>
    <p>Materials used in the project: <a class="about-links" href="https://uekkrakowpl-my.sharepoint.com/:w:/g/personal/231284_student_uek_krakow_pl/EYFSae8Cq39ErCQUx5WhlwwBUtsW8K3eKa_hzo80FWKCvA?e=5V4pEb">HERE</a></p>
    <p>Main inspiration for the project: <a class="about-links" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">HERE</a></p>
</div>

SimWeb/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Main project page";
}
<h1>@ViewData["Title"]</h1>
<div class="main-text">
    <form class="directions-form" method="get" asp-page="Simulation">
        <label for="directionInput">Enter the Directions (d, u, l, r only):</label>
        <input type="text"
               id="directionInput"
               name="moves"
               pattern="[dDuUlLrR]*"
               title="Only the letters d, u, l, and r (case insensitive) are allowed."
               maxlength="40"
               required>
        <button id="go" type="submit">GO!</button>
    </form>
</div>

SimWeb/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Site Name</title>
    <link rel="stylesheet" href="~/css/site.css"
          asp-append-version="true" />
    <script src="~/js/site.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jersey+10&family=Redacted+Script:wght@300;400;700&family=Rubik+Dirt&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="menu">
            <p class="menu-title">Michael Tryfanau's project</p>
            <a asp-area="" asp-page="/Index">Home</a>
            <a asp-area="" asp-page="/About">About</a>
        </nav>
    </header>
    <main>
        @RenderBody()
    </main>
    <footer>
        <p>
            Michael Tryfanau, 2025.
        </p>
    </footer>
</body>
</html>

SimWeb/Pages/Simulation.cshtml
@page
@model SimWeb.Pages.SimulationModel
@{
    ViewData["Title"] = "Simulation";
}
<h1>SIMULATION</h1>
<div class="steerers">
    <form asp-page-handler="Previous" method="post">
        <input type="hidden" name="Moves" value="@Model.Moves" />
        <button class="steerer" id="prev">Previous</button>
    </form>
    <form asp-page-handler="Next" method="post">
        <input type="hidden" name="Moves" value="@Model.Moves" />
        <button class="steerer" id="nxt">Next</button>
    </form>
</div>
@Html.Raw(Model.Field)